# ClawHub Registry Metadata
# This file explicitly declares registry-level metadata for ClawHub
# UPDATED: 2026-02-12 to force registry re-indexing

skill_name: iCalendar Sync
skill_version: 2.2.30
skill_type: runtime  # NOT instruction-only - this is a Python package with install.sh

# CRITICAL: Required credentials (MUST NOT BE EMPTY/NONE)
required_env_vars:
  - name: ICLOUD_USERNAME
    description: Apple ID email address
    type: string
    required: true
    sensitive: false

  - name: ICLOUD_APP_PASSWORD
    description: App-Specific Password from appleid.apple.com
    type: string
    required: true
    sensitive: true

# Primary credential
primary_credential: ICLOUD_APP_PASSWORD

# Optional environment variables
optional_env_vars:
  - name: DEFAULT_CALENDAR
    description: Default calendar name
    default: Personal

  - name: LOG_LEVEL
    description: Logging level
    default: INFO

# Installation type - EXPLICIT DECLARATION
install_type: script  # uses install.sh
install_script: install.sh
has_install_spec: true
instruction_only: false

# Capabilities
purpose: iCloud Calendar CalDAV synchronization
capabilities:
  - List calendars
  - Get calendar events
  - Create calendar events
  - Delete calendar events
  - Recurring events support
  - Multi-language support

# Security
security:
  credential_storage: OS keyring (macOS Keychain, Windows Credential Manager, Linux Secret Service)
  network_endpoints:
    - caldav.icloud.com:443
    - p*-caldav.icloud.com:443
  ssl_verification: enforced
  input_validation: true
  rate_limiting: 10 calls per 60 seconds
